import type { ModelConfig, ModelTier, ModelRouterConfig } from './types.js';

export const MISTRAL_CONFIG: ModelRouterConfig = {
  models: {
    small: {
      tier: 'small',
      modelName: 'mistral-small-latest',
      endpoint: 'https://api.mistral.ai/v1/chat/completions',
      apiKey: '',
      region: 'eu',
      maxTokens: 2048,
      temperature: 0.1,
      pricePerMTokenInput: 0.20,
      pricePerMTokenOutput: 0.60,
      hosting: 'cloud',
    },
    large: {
      tier: 'large',
      modelName: 'mistral-large-latest',
      endpoint: 'https://api.mistral.ai/v1/chat/completions',
      apiKey: '',
      region: 'eu',
      maxTokens: 4096,
      temperature: 0.2,
      pricePerMTokenInput: 2.00,
      pricePerMTokenOutput: 6.00,
      hosting: 'cloud',
    },
    medium: {
      tier: 'medium',
      modelName: 'mistral-medium-latest',
      endpoint: 'https://api.mistral.ai/v1/chat/completions',
      apiKey: '',
      region: 'eu',
      maxTokens: 8192,
      temperature: 0.3,
      pricePerMTokenInput: 2.70,
      pricePerMTokenOutput: 8.10,
      hosting: 'cloud',
    },
    embedding: {
      tier: 'embedding',
      modelName: 'mistral-embed',
      endpoint: 'https://api.mistral.ai/v1/embeddings',
      apiKey: '',
      region: 'eu',
      maxTokens: 8192,
      temperature: 0,
      pricePerMTokenInput: 0.12,
      pricePerMTokenOutput: 0,
      hosting: 'cloud',
    },
  },
  aiGatewayId: '',
  defaultRegion: 'eu',
  enableBatch: true,
  metadataReuseEnabled: true,
};

export const SELF_HOSTED_CONFIG: ModelRouterConfig = {
  models: {
    small: {
      tier: 'small',
      modelName: 'ministral-8b',
      endpoint: 'http://localhost:8080/v1/chat/completions',
      apiKey: 'not-needed',
      region: 'custom',
      maxTokens: 2048,
      temperature: 0.1,
      pricePerMTokenInput: 0,
      pricePerMTokenOutput: 0,
      hosting: 'self-hosted',
    },
    large: {
      tier: 'large',
      modelName: 'mistral-large-instruct',
      endpoint: 'http://localhost:8080/v1/chat/completions',
      apiKey: 'not-needed',
      region: 'custom',
      maxTokens: 4096,
      temperature: 0.2,
      pricePerMTokenInput: 0,
      pricePerMTokenOutput: 0,
      hosting: 'self-hosted',
    },
    medium: {
      tier: 'medium',
      modelName: 'mistral-medium-instruct',
      endpoint: 'http://localhost:8080/v1/chat/completions',
      apiKey: 'not-needed',
      region: 'custom',
      maxTokens: 8192,
      temperature: 0.3,
      pricePerMTokenInput: 0,
      pricePerMTokenOutput: 0,
      hosting: 'self-hosted',
    },
    embedding: {
      tier: 'embedding',
      modelName: 'mistral-embed',
      endpoint: 'http://localhost:8080/v1/embeddings',
      apiKey: 'not-needed',
      region: 'custom',
      maxTokens: 8192,
      temperature: 0,
      pricePerMTokenInput: 0,
      pricePerMTokenOutput: 0,
      hosting: 'self-hosted',
    },
  },
  aiGatewayId: '',
  defaultRegion: 'custom',
  enableBatch: true,
  metadataReuseEnabled: true,
};

export function createConfig(hosting: 'cloud' | 'self-hosted' = 'cloud', overrides?: Partial<ModelRouterConfig>): ModelRouterConfig {
  const base = hosting === 'self-hosted' ? SELF_HOSTED_CONFIG : MISTRAL_CONFIG;
  return {
    ...base,
    ...overrides,
    models: { ...base.models, ...overrides?.models },
  };
}